### ISSUE TITLE
Guidance on "learn more"

### ISSUE THREAD

**Issue by jkshapiro** [gctools-outilsgc/design-system-code#230]
On the page https://design.gccollab.ca/content/system-vocabulary, the phrase "Learn more" is suggested as a common call to action. It is, but it's also not very useful for people using screen readers and tabbing from link to link.

Instead of just "learn more", an accessible call to action should say "learn more about &lt;whatever&gt;".

**Comment by s-duffey** [comment]
Good call. Will be modified in next update.

**Comment by s-duffey** [comment]
Looking at this further, the same would need to be said about most phrases on this page. Since this information is given elsewhere (i.e. with specific elements) that titles need additional context in alt text, it doesn't make sense to reiterate that again on this specific phrase. The system vocabulary is more for reference only, and isn't a set list of how terms need to be used.
